### ISSUE TITLE
libx68kへのパッチを作成しました。

### ISSUE THREAD

**Issue by kazuwai1** [yunkya2/elf2x68k#2]
かずわいと申します。
以下の動作を修正するためのパッチを添付します。
・stdio利用中にfstat()を使うとファイルの読み出し位置が狂う
・fgets()でstdin(キーボード)から入力を行うと改行を入力しても呼出元へ戻らない

[diff.txt](https://github.com/yunkya2/elf2x68k/files/13319103/diff.txt)

ご確認いただければ幸いです。

**Comment by yunkya2** [comment]
ご報告ありがとうございます。
e27a9fd
74cb845
で取り込ませていただきました。
