### ISSUE TITLE
elf2x68k の stdio の rename() について

### ISSUE THREAD

**Issue by kazuwai1** [yunkya2/elf2x68k#3]
elf2x68k環境でソースコードをコンパイルする際に、stdioのrename()を使用していると「_rename()が無いよ」とリンクエラーが発生するようです。
自分の使用しているローカル環境で確認したところ、elf2x68k/src/libx68k/rename.c の中の  rename()を _rename() に変更すると辻褄があってリンクエラーにならないようです。

可能であれば変更を検討いただければと思います。

--
twitter: kazuwai1 / かずわい

**Comment by yunkya2** [comment]
ご報告ありがとうございます。
f848bc6 で修正しました。
