### ISSUE TITLE
x68k2elf.pyで変換したオブジェクトで.quad/.alignが有効にならない

### ISSUE THREAD

**Issue by kg68k** [yunkya2/elf2x68k#5]
version: 20240716

`.quad`または`.align`疑似命令を使用したアセンブラ用ソースコードをHAS060.Xでアセンブルし、
x68k2elf.pyでELF形式に変換してm68k-xelf-gccでmain()関数とリンクし実行ファイルを作成すると、`.quad`/`.align`疑似命令が有効になりません。

## 再現手順

a.s
```
.data
.quad
_a:: .dc.b 1
```

b.s
```
.data
.quad
_b:: .dc.b 2
```

main.c
```
#include <stdio.h>

extern char a, b;

int main (void) {
  int aa = ((int)&a) & 15;
  int bb = ((int)&b) & 15;
  printf ("%d, %d\n", aa, bb);
  return 0;
}
```

上記ファイルをHuman68k上で
```
has060 a.s
has060 b.s
gcc2 -O2 -o main.x main.c a.o b.o
./main
```
とすると、`4, 8`のようにいずれも4バイト境界にアラインされた値が表示されます。

上記手順で作成したa.o、b.oをelf2x68k環境に持ち込み
```
x68k2elf.py a.o a_elf.o
x68k2elf.py b.o b_elf.o
m68k-xelf-gcc -O2 -o main.x main.c a_elf.o b_elf.o
```
とし作成されたmain.xをHuman68k上で実行すると、`4, 6`のようにどちらかが4バイト境界にアラインされていない値が表示されます。

[aligntest.zip](https://github.com/user-attachments/files/17092530/aligntest.zip)

**Comment by yunkya2** [comment]
こちらも報告ありがとうございます。
確認してみたところ、そもそもX68kのオブジェクトファイルのアラインメント情報は、HAS.Xの時に私自身が仕様を決めて追加したものだったんですね。完全に忘れていました…。
f80cd94 で、*.oの拡張アラインメント情報をELF側に反映させる変更を追加しました。

**Comment by kg68k** [comment]
ありがとうございます。
指定通りアラインされるようになりました。
