### ISSUE TITLE
[libx68k] write()で改行変換時にバッファオーバーフロー

### ISSUE THREAD

**Issue by kg68k** [yunkya2/elf2x68k#6]
https://github.com/yunkya2/elf2x68k/blob/master/src/libx68k/write.c

write()では出力先が端末やテキストモードのとき改行コードの\nから\r\nへの変換が行われますが、256バイトの`textbuf`バッファに255バイト書き込んだ時点で\nが来ると、\r\nの2バイトを書き込むためバッファオーバーフローが発生するのではないかと思います。

ただ現在のコンパイル結果ではスタック上に確保された`char textbuf[TEXTBUFSIZE];`の直後には`char ch;`が配置されているようで、そのため動作に影響があるような形でのスタック破壊はおきず、_dos_write()での257バイトの書き出しも期待するのと同じ結果が得られているようです。

```c
#include <stdio.h>
#include <string.h>

int main(void) {
  char buf[256];
  memset(buf, 'a', sizeof(buf));
  buf[sizeof(buf) - 1] = '\n';

  FILE* fp = fopen("test.txt", "wt");
  if (!fp) return 1;
  fwrite(buf, 1, sizeof(buf), fp);
  fclose(fp);

  return 0;
}
```

**Comment by yunkya2** [comment]
報告ありがとうございます。
確かに、たまたま期待通りの動作になるだけでバッファオーバーフローしてますね。修正します。
最低限はバッファサイズを広げるだけでも回避できますが、半端なサイズの_dos_write()を許容するかどうかですね。

**Comment by kg68k** [comment]
効率面でいうとread()で\r\nの多いファイルを読んだときに_dos_read()を繰り返すというのもありますし、もっと広く捉えると改行の変換をどのように実現するかという命題とも考えられます。

例えば以下のコードはLinuxやVisual Studioでは期待通りの出力が得られますが、LIBCやelf2x68kではうまくいきません。
```c
#include <stdio.h>

int main(void) {
  const char file[] = "test.txt";

  FILE* fp = fopen(file, "wt");
  if (!fp) return 1;
  fputs("a\nb\n", fp);
  fclose(fp);

  fp =  fopen(file, "r+t");
  if (!fp) return 1;
  fgetc(fp);  // read 'a'
  fgetc(fp);  // read '\n'
  fseek(fp, ftell(fp), SEEK_SET);
  fputc('X', fp);  // intend to overwrite 'b' with 'X'
  fclose(fp);

  return 0;
}
```
これ自体一つのissueとして扱うべきなんですが、どこまでがんばるか的な話ですね…。

**Comment by yunkya2** [comment]
確かに…。
ひとまず、最低限のバッファオーバーフローの修正を行っておきます。

**Comment by yunkya2** [comment]
bfe539e でバッファオーバーフローの修正を行いました。

**Comment by kg68k** [comment]
ありがとうございます。
